# development:
#   secret_key_base: e92ab8872c64389bb18d4a2d99b503a7041f4945976dc5dd01807997deacdb8f40b4e0457ed1b0a977ee29881549061d0d50d75185b66b613f460b0b11854aec
#   stripe_publishable_key: pk_test_nSPW0TLbqhRptM5c6ZIH4l2O
#   secret_key: sk_test_QFJO3X47Fz4hH4FXNksJFXh6

production:
  secret_key_base: <%= ENV["secret_key_base"] %>
  stripe_publishable_key: <%= ENV["stripe_publishable_key"] %>
  secret_key: <%= ENV["secret_key"] %>
